/ FILE: pubspec.yaml // Modernized Flutter shopping app with animations

name: flutter_shopping_app_modern description: Modern shopping demo app with animations built with Flutter and Dart. version: 1.0.0+1 publish_to: 'none'

environment: sdk: ">=2.18.0 <4.0.0"

dependencies: flutter: sdk: flutter provider: ^6.0.5 lottie: ^2.4.0

dev_dependencies: flutter_test: sdk: flutter flutter_lints: ^2.0.0

flutter: uses-material-design: true
